/**
 * Define additional input action types here
 * Give an enum name, followed by a string value
 */
export enum InputAction {
  MOVE_UP = "MOVE_UP",
  MOVE_DOWN = "MOVE_DOWN",
  MOVE_LEFT = "MOVE_LEFT",
  MOVE_RIGHT = "MOVE_RIGHT",
  PICK_UP = "PICK_UP",
  DROP = "DROP",
  FULFILL = "FULFILL",
  JUMP = "JUMP",
  SPRINT = "SPRINT",
  ATTACK = "ATTACK",
  INVENTORY1 = "INVENTORY1",
  INVENTORY2 = "INVENTORY2",
  INVENTORY3 = "INVENTORY3",
  INVENTORY4 = "INVENTORY4",
  INVENTORY5 = "INVENTORY5",
  INVENTORY6 = "INVENTORY6",
  INVENTORY7 = "INVENTORY7",
  INVENTORY8 = "INVENTORY8",
  INVENTORY9 = "INVENTORY9",
  PAUSE = "PAUSE"
}